plugins {
    alias(libs.plugins.template.android.application)
    alias(libs.plugins.template.android.application.compose)
    alias(libs.plugins.template.android.hilt)
    alias(libs.plugins.template.android.application.jacoco)
    alias(libs.plugins.baselineprofile)
}

android {
    namespace = "android.template"

    defaultConfig {
        applicationId = "android.template"
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "android.template.core.testing.HiltTestRunner"

        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

baselineProfile {
    // Don't generate Baseline Profiles during normal builds (that requires a device/emulator).
    // Generate them explicitly through the :benchmarks module when a device is available.
    automaticGenerationDuringBuild = false
}

dependencies {
    implementation(projects.core.ui)
    implementation(projects.feature.mymodel.api)
    implementation(projects.feature.mymodel.impl)
    implementation(projects.sync.work)

    // Core Android dependencies
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.profileinstaller)

    // Hilt Dependency Injection (extra KSP processors for test source sets)
    kspAndroidTest(libs.hilt.compiler)
    kspTest(libs.hilt.compiler)

    // Arch Components
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)

    // Compose
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.material3)

    // Navigation
    implementation(projects.core.navigation)
    implementation(libs.androidx.navigation3.ui)
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)

    // Instrumented tests
    androidTestImplementation(projects.core.testing)
    androidTestImplementation(projects.uiTestHiltManifest)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.hilt.android.testing)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)

    // Baseline Profiles are generated by the :benchmarks module.
    baselineProfile(projects.benchmarks)
}
